#!/bin/bash
  
###############################################################################
# This script installs spacemacs using Coder's personalize script. The base
# image must include emacs. This script runs each time the environment is
# rebuilt. The script must be located at ~/personalize. The initial environment
# will not contain this script, so it must be added after creation.
###############################################################################


# Backup existing emacs files if they exist
if [ -d ~/.emacs.d ]; then
        echo "Backing up ~/.emacs.d"
        mv ~/.emacs.d ~/.emacs.d.bak
fi

if [ -f ~/.emacs ]; then
        echo "Backing up ~/.emacs"
        mv ~/.emacs ~/.emacs.bak
fi

# Install spacemacs
echo "Cloning spacemacs"
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
